version: '3.7'

networks:
  wayfinder:

volumes:
  postgres:
  influxdb:
  chronograf:

services:
  logstash:
    image: ghcr.io/unikraft/wayfinder/logstash:latest
    hostname: logstash
    container_name: wayfinder-logstash
    restart: on-failure
    build:
      context: support/logstash
    volumes:
      - ./support/logstash/pipeline:/usr/share/logstash/pipeline-templates
      - ./support/logstash/config:/usr/share/logstash/config
      - ./support/logstash/init:/opt/docker-init
    environment:
      INPUT_PORT: 12345
      OUTPUT_HOST: wayfinder-influxdb
      OUTPUT_PORT: 8086
      OUTPUT_USER: wayfinder
      OUTPUT_PASS: wayfinder
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      http_proxy: ""
      https_proxy: ""
    ports:
      - 12345:12345
    networks:
      - wayfinder

  influxdb:
    image: influxdb:1.4-alpine
    container_name: wayfinder-influxdb
    hostname: influxdb
    restart: on-failure
    stdin_open: true
    volumes:
     - influxdb:/var/lib/influxdb
    # env_file: ./.env
    ports:
     - 8086:8086
    networks:
      - wayfinder
    environment:
      INFLUXDB_DB: wayfinder
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: wayfinder
      INFLUXDB_ADMIN_PASSWORD: wayfinder
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      http_proxy: ""
      https_proxy: ""

  chronograf:
    image: chronograf:latest
    hostname: chronograf
    container_name: wayfinder-chronograf
    restart: on-failure
    volumes:
     - chronograf:/var/lib/chronograf
    ports:
     - 8888:8888
    command: --influxdb-url=http://influxdb:8086
    networks:
      - wayfinder
    environment:
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      http_proxy: ""
      https_proxy: ""

  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    container_name: wayfinder-grafana
    ports:
      - 3000:3000/tcp
    volumes:
      - ./support/grafana/dashboards:/var/lib/grafana/dashboards
      - ./support/grafana/dashboards_config:/etc/grafana/provisioning/dashboards
      - ./support/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./support/grafana/plugins:/var/lib/grafana/plugins
    # env_file: ./.env
    environment:
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      http_proxy: ""
      https_proxy: ""
      GF_DASHBOARDS_JSON_ENABLED: "true"
      GF_SECURITY_ADMIN_PASSWORD: wayfinder
      GF_SECURITY_ADMIN_USER: wayfinder
      GF_SECURITY_SECRET_KEY: 1234
    networks:
      - wayfinder
  
  redis:
    image: redis:6.2.6-alpine
    hostname: redis
    container_name: wayfinder-redis
    restart: on-failure
    env_file: ./.env
    command:
      - redis-server
      - --requirepass "${REDIS_PASSWORD:-redis}"
    ports:
      - 6379:6379
    networks:
      - wayfinder    

  postgres:
    image: postgres:latest
    container_name: wayfinder-postgres
    hostname: postgres
    restart: on-failure
    env_file: ./.env
    ports:
      - 5432:5432
    networks:
      - wayfinder
    volumes:
      - postgres:/var/lib/postgresql/data

  registry:
    image: registry:2
    container_name: wayfinder-registry
    hostname: registry
    restart: on-failure
    env_file: ./.env
    ports:
      - 5000:5000
    networks:
      - wayfinder

  wayfinder:
    image: ghcr.io/unikraft/wayfinder:latest
    container_name: wayfinder
    depends_on:
      - redis
      - postgres
    restart: on-failure
    env_file: ./.env
    volumes:
      - .:/go/src/github.com/unikraft/wayfinder
    ports:
      - 8080:8080
      - 5000:5000
    networks:
      - wayfinder
