# SPDX-License-Identifier: BSD-3-Clause
#
# Authors: Alexander Jung <alex@unikraft.io>
#
# Copyright (c) 2021, Unikraft UG.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# HTTP Server
# ===========
#
# This option exposes a HTTP API REST server on the daemon.  Endpoints will be
# made available which can be used to manipulate jobs and permutations.
http-server:
  addr: ":8080"

# Health Status
# =============
#
# This option provides a healthz check to determine the status of the daemon.
health:

# gRPC Server
# ===========
#
# This option allows for exposing a gRPC server on the daemon which can be used
# by a client to make well-defined RPC requests using the provided SDK.
grpc-server:
  addr: ":7000"

# Server Register
# ===============
#
# This is an internal option which allows for the existence of other modules,
# plugins and connections to distributed services.
service-register:

# Postgres Client
# ===============
#
# Connect wayfinder to a remote postgres client to save information about jobs,
# permutations and more long-term. 
#
postgres:
  host: "${POSTGRES_HOST:postgres}"
  port: ${POSTGRES_PORT:5432}
  user: "${POSTGRES_USER:wayfinder}"
  log_queries: "${POSTGRES_LOG_QUERIES:false}"
  password: "${POSTGRES_PASSWORD:wayfinder}"
  database: "${POSTGRES_DATABASE:wayfinder}"
  ssl_enable: "${POSTGRES_SSL_ENABLE:false}"
  ssl_rootcert: "${POSTGRES_SSL_ROOTCERT:}"
  ssl_cert: "${POSTGRES_SSL_CERT:}"
  ssl_key: "${POSTGRES_SSL_KEY:}"

# Host Configurator
# =================
#
# The host configurator sets idiomatic and static values for performing 
# isolated and controlled experiments on job permutations.
#
hostconfig:
  cpu_sets: 2-7
  scaling_governor: performance
  procfs:
    # Filesystem
    # - /proc/sys/fs/file-max:20000
    # - /proc/sys/vm/drop_caches:3

    # Networking
    # - /proc/sys/net/core/somaxconn:1024
    - /proc/sys/net/ipv4/ip_forward:1
    # - /proc/sys/net/ipv4/ip_local_port_range:1024   60999
    # - /proc/sys/net/ipv4/tcp_keepalive_time:60
    # - /proc/sys/net/ipv4/tcp_keepalive_intvl:60
    # - /proc/sys/net/ipv4/tcp_tw_reusee:1

    # Processor
    # - /sys/devices/system/cpu/intel_pstate/no_turbo:1

    # Memory
    # - /proc/sys/kernel/randomize_va_space:0
    # - /proc/sys/kernel/unprivileged_userns_clone:1

# Redis Client
# ============
#
# Provision to connect to a redis server.  This is used to store the state of 
# requested jobs and their permutations which will be passed to the scheduler.
#
redis:
  master_name: "master"
  addr: "${REDIS_ADDR:localhost:6379}"
  password: "${REDIS_PASSWORD:redis}"


# libvirt Client
# ==============
#
# Provision to connect to the libvirt daemon with additional control parameters 
# for the runtime of virtual machines.
#
libvirt:
  # Connection endpoint to the libvirt daemon service
  endpoint: qemu:///system

  # Emulator to use to launch virtual machines
  emulator: /usr/bin/qemu-system-x86_64

  # Path to list of runtime virtual machine's sockets.
  sockdir: /run/libvirt/qemu/

  # Timeout for when making connections to libvirt
  timeout: 60s

  # Name of the shared bridge for virtual machines.
  bridge: wayfinder0

  # Host interface to connect the bridge to.
  host_iface: eth0

  # State directory where on-going connections to the bridge are saved.
  bridge_statedir: /tmp/lib/wayfinder/bridges

  # The subnet for containers to use
  subnet: 172.88.0.1/24

  # Directory to store the complete log of the virtual machine's output.
  logdir: /var/lib/wayfinder/logs

  # Path to the proc filesystem
  procf: /proc

  # Frequency (in seconds) for collecting metrics
  measure_freq: 1s

  # Enable CPU metrics
  measure_cpu: true

  # Enable memory metrics
  measure_mem: true

  # Enable network metrics
  measure_net: true

# Job Service
# ===========
#
# This service handles incoming jobs, parsing them for validty from the queue
# and begins to populate the permutation queue.
#
job:
  # Queue pre-fetch limit is used to limit the number of jobs which are consumed
  prefetch_limit: ${JOB_PREFETCH_LIMIT:1}

  # The amount of time to timeout from the Redis queue
  poll_duration: ${JOB_POLL_DURATION:100ms}

# Scheduler Service
# =================
#
# The scheduler picks up permutations from the Redis queue and decides whether
# to run the particular permutation or reject it.  On schedule, it will oversee
# the build and test of the permutation on designated cores.
#
scheduler:
  # Queue pre-fetch limit is used to limit the number of permutations which are 
  # consumed
  prefetch_limit: ${SCHEDULER_PREFETCH_LIMIT:1}

  # The amount of time to timeout from the Redis queue
  poll_duration: ${SCHEDULER_POLL_DURATION:100ms}

  # Amount of time to wait in between scheduling permutations
  grace_time: "${SCHEDULER_GRACE_TIME:3s}"

  # Number of times to re-try the permutation in case it fails
  max_retries: ${SCHEDULER_MAX_RETRIES:3}

# Container Service
# =================
#
# The container service is a generic internal module to facilitate the runtime
# of containers.  Used by both build and test jobs.
#
container:
  # Path to cache and filesystems of containers.  Hot tip: place this in /tmp
  # to make things run faster!
  rootdir: ${CONTAINER_ROOTDIR:/tmp/lib/wayfinder/containers}

  # The directory to save container OCI archives
  cachedir: ${CONTAINER_CACHEDIR:/tmp/lib/wayfinder/cache}

  # The directory to save container unpacked images for jobs
  saveddir: ${CONTAINER_SAVEDDIR:/tmp/lib/wayfinder/saved}

  # Path to save logs to from container runtimes
  logdir: ${CONTAINER_LOGDIR:/var/lib/wayfinder/logs}

  # The address of the registry where to back up images
  registry: ${REGISTRY_ADDR:localhost:5000}

  # The networking bridge cache dir used for saving the state of networking
  bridge_statedir: ${CONTAINER_BRIDGE_STATEDIR:/tmp/lib/wayfinder/bridges}

  # Host network interface to connect the bridge to to access the wider area 
  # network.
  host_iface: ${CONTAINER_HOST_IFACE:eth0}

  # Name of the shared bridge for containers
  bridge: ${CONTAINER_BRIDGE:wayfinder0}

  # The subnet for containers to use
  subnet: ${CONTAINER_SUBNET:172.88.0.1/24}

  # Default environmental variables to add to each container
  environment:
    - TERM=xterm
    - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Builder Service
# ===============
#
# The builder service facilitates the runtime of a permutation's build by 
# interacting with the container service and oversees its runtime and status.
#
builder:
  # Path on the host to output artifacts from a build.
  outputdir: /tmp/wayfinder/builds/

  # Timeout for killing a build (which may take too long).  Setting this to zero
  # means there is no timeout.
  kill_timeout: 10m

  # How many attempts the build should be tried before we give up on it.
  retries: 3

# Tester Service
# ==============
#
# The tester service facilitates the test by launching the virtual machine 
# which results from a successful build.  The test will begin when the 
# benchtool has started, which receives information about the VM.
#
tester:
  # The default amount of time to wait between starting the VM and starting the 
  # benchmark tool.  Also known as the "VM warm up period"
  default_start_delay: ${TESTER_DEFAULT_START_DELAY:5s}

  # Frequency (in seconds) for pushing metrics
  metrics_freq: 1s

  # Mechanic to connect to the metrics receiver.
  metrics_receiver_type: tcp

  # Location of the remote metrics receiver.
  metrics_receiver: 127.0.0.1:8086
