# SPDX-License-Identifier: BSD-3-Clause
#
# Authors: Alexander Jung <alex@unikraft.io>
#
# Copyright (c) 2021, Unikraft UG.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# HTTP Server
# ===========
#
# This option exposes a HTTP API REST server on the daemon.  Endpoints will be
# made available which can be used to manipulate jobs and permutations.
http-server:
  addr: ":8080"

# Health Status
# =============
#
# This option provides a healthz check to determine the status of the daemon.
health:

# gRPC Server
# ===========
#
# This option allows for exposing a gRPC server on the daemon which can be used
# by a client to make well-defined RPC requests using the provided SDK.
grpc-server:
  addr: ":5000"

# Server Register
# ===============
#
# This is an internal option which allows for the existence of other modules,
# plugins and connections to distributed services.
service-register:

# Host Configurator
# =================
#
# The host configurator sets idiomatic and static values for performing 
# isolated and controlled experiments on job permutations.
#
hostconfig:
  # TODO: Use this number in scheduler's coremap by evicting cores not in this
  # list/var
  cpu_sets: 20-30
  scaling_governor: performance
  procfs:
    # Filesystem
    - /proc/sys/fs/file-max:20000
    # - /proc/sys/vm/drop_caches:3

    # Networking
    - /proc/sys/net/core/somaxconn:1024
    - /proc/sys/net/ipv4/ip_forward:1
    - /proc/sys/net/ipv4/ip_local_port_range:1024   60999
    - /proc/sys/net/ipv4/tcp_keepalive_time:60
    - /proc/sys/net/ipv4/tcp_keepalive_intvl:60
    # - /proc/sys/net/ipv4/tcp_tw_reusee:1

    # Processor
    - /sys/devices/system/cpu/intel_pstate/no_turbo:1

    # Memory
    - /proc/sys/kernel/randomize_va_space:0
    - /proc/sys/kernel/unprivileged_userns_clone:1
