#!/bin/bash


# Extract on/off options from the webpage
options=$(curl -s https://www.sqlite.org/pragma.html | grep -oE "PRAGMA [a-zA-Z_]* = </b><i>boolean" | grep -oE "PRAGMA [a-z_]*" | grep -oE "[a-z_]*")

# Convert newline separated list to bash array
readarray -t <<< $options

# Print disclaimer
echo "# Auto-generated by extract-sqlite-options.sh on $(date +%Y-%m-%d)"

# Convert to yaml format
for option in ${options[@]}; do
    echo "  # PRAGMA $option"
    echo "  - name:    ${option^^}"
    echo "    type:    string"
    echo "    only:    [\"on\", \"off\"]"
    echo "    when:    test"
    echo ""
done


