#user  nobody;
worker_processes  1;
daemon off;
master_process off;
worker_rlimit_nofile $WORKER_RLIMIT_NOFILE;

events {
  worker_connections  $WORKER_CONNECTIONS;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    server_tokens $SERVER_TOKENS;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    access_log $ACCESS_LOG;

    sendfile $SENDFILE;
    tcp_nopush $TCP_NOPUSH;

    keepalive_timeout  $KEEPALIVE_TIMEOUT;

    # Commented block taken from https://github.com/risan/nginx-config/blob/master/nginx.conf
    # Enable gzip compression.
    # gzip on;

    # Gzip compression level (1-9).
    # 5 is a perfect compromise between size and CPU usage, offering about
    # 75% reduction for most ASCII files (almost identical to level 9).
    # gzip_comp_level 5;

    # Don't compress a small file that is unlikely to shrink much. The small
    # file is also usually ended up in larger file sizes after gzipping.
    # gzip_min_length 256;

    # Compress data even for a proxied connection.
    # gzip_proxied any;

    # Cache both the regular and the gzipped versions of a resource whenever
    # client's Accept-Encoding capabilities header varies.
    # gzip_vary on;

    server {
        listen       80;
        server_name  localhost;

        location / {
            root   html;
            index  index.html index.htm;
        }
    }
}
