bind 0.0.0.0
port 6379
protected-mode no
daemonize no
supervised no
maxclients 10000
maxmemory 

loglevel notice
logfile ""
syslog-enabled no
always-show-logo no
stop-writes-on-bgsave-error no
dbfilename dump.rdb
dir /

tcp-backlog %REDIS_TCP_BACKLOG%

timeout %REDIS_TIMEOUT%
tcp-keepalive %REDIS_KEEPALIVE%

databases %REDIS_DATABASE%

save %REDIS_SAVE_TIME% %REDIS_SAVE_RECORDS%

rdbcompression %REDIS_RBCOMRESSION%
maxmemory-policy %REDIS_MAX_MEMORY_POLICY%
maxmemory-samples %REDIS_MAX_MEMORY_SAMPLE%

appendonly %REDIS_APPEND_ONLY%
appendfilename "appendonly.aof"
appendfsync %REDIS_APPEND_FSYNC%
no-appendfsync-on-rewrite %REDIS_APPEND_FSYNC_REWRITE%
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

aof-load-truncated yes
aof-use-rdb-preamble no

slowlog-max-len 128

hash-max-ziplist-entries 512
hash-max-ziplist-value 64
list-max-ziplist-size -2
list-compress-depth 0


set-max-intset-entries 512

zset-max-ziplist-entries 128
zset-max-ziplist-value 64


client-output-buffer-limit normal 0 0 0
client-output-buffer-limit slave 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60
#
# lfu-log-factor 10
# lfu-decay-time 1


activedefrag yes
active-defrag-ignore-bytes 100mb

# Minimum percentage of fragmentation to start active defrag
# active-defrag-threshold-lower 10

# Maximum percentage of fragmentation at which we use maximum effort
# active-defrag-threshold-upper 100

# Minimal effort for defrag in CPU percentage
# active-defrag-cycle-min 25

# Maximal effort for defrag in CPU percentage
# active-defrag-cycle-max 75
