{
 "title": "wayfinder: bottleneck detection",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "host_name",
    "query": "SELECT \"host_name\" FROM (SELECT last(\"cpu_cores\") FROM \"wayfinder.domains\" WHERE $timeFilter GROUP BY \"host_name\" fill(none))"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Steal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n sum(\"mean_cpu_steal\")  AS \"vm_cpu_steal\"\nFROM \n( SELECT mean(\"cpu_steal\") AS \"mean_cpu_steal\" FROM \"wayfinder\".\"autogen\".\"wayfinder.domains\" WHERE (\"host_name\" =~ /^$host_name$/)  AND $timeFilter GROUP BY time($__interval), \"UUID\" FILL(none) )\nGROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Queue Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n sum(\"mean_disk_device_queuesize\")  AS \"host_disk_queuesize\"\nFROM \n( SELECT mean(\"disk_device_queuesize\") AS \"mean_disk_device_queuesize\" FROM \"wayfinder\".\"autogen\".\"wayfinder.hosts\" WHERE (\"host_name\" =~ /^$host_name$/)  AND $timeFilter GROUP BY time($__interval), \"host_name\" FILL(none) )\nGROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n sum(\"mean_network_received\")  AS \"vm_network_received\",\n sum(\"mean_network_transmitted\") AS \"vm_network_transmitted\"\nFROM \n( SELECT mean(\"net_receivedBytes\") AS \"mean_network_received\", mean(\"net_transmittedBytes\") AS \"mean_network_transmitted\" FROM \"wayfinder\".\"autogen\".\"wayfinder.domains\" WHERE (\"host_name\" =~ /^$host_name$/)  AND $timeFilter GROUP BY time($__interval), \"UUID\" FILL(none) )\nGROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n sum(\"mean_speed\")  AS \"host_network_speed\"\nFROM \n( SELECT mean(\"net_host_speed\") *1024*1024/8 AS \"mean_speed\" FROM \"wayfinder\".\"autogen\".\"wayfinder.hosts\" WHERE (\"host_name\" =~ /^$host_name$/)  AND $timeFilter GROUP BY time($__interval), \"host_name\" FILL(none) )\nGROUP BY time($__interval) FILL(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}