bind 0.0.0.0
port 6379
protected-mode no
daemonize no
supervised no
maxclients 10000

loglevel notice
logfile ""
syslog-enabled no
always-show-logo no
stop-writes-on-bgsave-error no
dbfilename dump.rdb
dir /tmp/

tcp-backlog %REDIS_TCP_BACKLOG%

timeout %REDIS_TIMEOUT%
tcp-keepalive %REDIS_KEEPALIVE%

databases %REDIS_DATABASES%

save ""

rdbcompression %REDIS_RBCOMRESSION%
rdbchecksum %REDIS_RDBCHECKSUM%
maxmemory 256mb
maxmemory-policy %REDIS_MAX_MEMORY_POLICY%
maxmemory-samples %REDIS_MAX_MEMORY_SAMPLE%

appendonly %REDIS_APPENDONLY%
appendfilename "appendonly.aof"
appendfsync %REDIS_AOF%
no-appendfsync-on-rewrite %REDIS_AOF_REWRITE%
auto-aof-rewrite-percentage %REDIS_AOF_PERCENT%
auto-aof-rewrite-min-size %REDIS_AOF_SIZE%mb

slowlog-log-slower-than 10000
slowlog-max-len %REDIS_SLOWLOG_LEN%

latency-monitor-threshold 0

hash-max-listpack-entries %REDIS_HASH_ENTRIES%
hash-max-listpack-value %REDIS_HASH_VALUES%
list-max-ziplist-size %REDIS_LISTPACK_SIZE%
list-compress-depth %REDIS_COMPRESS%


set-max-intset-entries %REDIS_INTSET%

zset-max-listpack-entries %REDIS_ZSET_ENTRIES%
zset-max-listpack-value %REDIS_ZSET_VALUES%


activerehashing %REDIS_REHASHING%

# These are hardlimits for when to disconnect clients.
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit slave 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60
#
# lfu-log-factor 10
# lfu-decay-time 1

# Expect these params will have no impact when running the default
# redis workload. I will leave them here, in case we need them later.
#active-defrag-ignore-bytes 100mb

# Minimum percentage of fragmentation to start active defrag
# active-defrag-threshold-lower 10

# Maximum percentage of fragmentation at which we use maximum effort
# active-defrag-threshold-upper 100

# Minimal effort for defrag in CPU percentage
# active-defrag-cycle-min 25

# Maximal effort for defrag in CPU percentage
# active-defrag-cycle-max 75

jemalloc-bg-thread %REDIS_JEMALOC_THREAD%
